# The URL the site will be built for
base_url = "https://midorikawa.me"
title = "M*2"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  { name = "topics", feed = false, render = true },
  { name = "series", feed = false, render = true }
]

[markdown]

[markdown.highlighting]
theme = "nord"

[extra]
# Put all your custom variables here
